title: pentland.ml
short_title: pentland.ml
baseurl:
permalink: "/:path/"
theme: minima
defaults:
  - scope:
      path: ""
    values:
      layout: page
  - scope:
      path: ""
      type: posts
    values:
      layout: post
collections:
  posts:
    output: true
gems:
  - jekyll-menus
  - jekyll-feed
